# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6
    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: KEY=${MAP_KEY} npm run test

  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:6
    working_directory: ~/repo

    steps:
      - add-ssh-keys:
          fingerprints:
            - "89:cc:8b:aa:17:24:65:08:de:aa:0a:e6:4b:61:43:50"

      - checkout

      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

      - run: git config --global user.email "qfoori@gmail.com"

      - run: git config --global user.name "shunsuke"

      - run: git config --global push.default matching

      - run: git show-branch

      - run: npm version patch

      - run: git push origin production && git push --tags

      - run: npm publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
      - deploy:
          context: org-global
          filters:
            branches:
              only: production
          requires:
            - build

